# Generated by Django 5.2.17 on 2026-08-28 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('expense', 'Expense'), ('buy', 'Buy'), ('sell', 'Sell')], max_length=12)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=8, max_digits=24, null=True)),
                ('price_at_tx', models.DecimalField(blank=True, decimal_places=2, help_text='Asset price at time of transaction', max_digits=18, null=True)),
                ('category', models.CharField(blank=True, choices=[('food', 'Food'), ('transport', 'Transport'), ('subscriptions', 'Subscriptions'), ('housing', 'Housing'), ('leisure', 'Leisure'), ('other', 'Other')], max_length=20, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.island')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['island', 'date'], name='ledger_tran_island__3705e8_idx'), models.Index(fields=['user', 'date'], name='ledger_tran_user_id_a0e87e_idx')],
            },
        ),
    ]
