# Generated by Django 5.2.17 on 2026-09-19 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0002_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(blank=True, choices=[('food', 'Food'), ('transport', 'Transport'), ('subscriptions', 'Subscriptions'), ('housing', 'Housing'), ('leisure', 'Leisure'), ('health', 'Salud'), ('clothing', 'Ropa'), ('travel', 'Viajes'), ('education', 'Educación'), ('finance', 'Finanzas'), ('family_events', 'Eventos Familiares'), ('taxes', 'Impuestos'), ('work', 'Trabajo'), ('sport', 'Deporte'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
