class ErrorCodes:
    AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED"
    NOT_AUTHENTICATED = "NOT_AUTHENTICATED"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    NOT_FOUND = "NOT_FOUND"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    THROTTLED = "RATE_LIMIT_EXCEEDED"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    UNKNOWN = "UNKNOWN_ERROR"
    OAUTH_ERROR = "OAUTH_ERROR"
    DJANGO_VALIDATION_ERROR = "VALIDATION_ERROR"  # reusa el mismo si aplica
    RESOURCE_EXISTS = "RESOURCE_CONFLICT"
    INVALID_REFERENCE = "INVALID_REFERENCE"
    DATA_INTEGRITY_ERROR = "DATA_INTEGRITY_ERROR"
    DATABASE_ERROR = "DATABASE_ERROR"
    SERVICE_TIMEOUT = "SERVICE_TIMEOUT"
    SERVICE_UNAVAILABLE = "SERVICE_UNAVAILABLE"
    EXTERNAL_API_ERROR = "EXTERNAL_API_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"

# Mapeo por default_code que ya trae DRF en sus excepciones built-in
DEFAULT_CODE_MAP = {
    "authentication_failed": ErrorCodes.AUTHENTICATION_FAILED,
    "not_authenticated": ErrorCodes.NOT_AUTHENTICATED,
    "permission_denied": ErrorCodes.PERMISSION_DENIED,
    "not_found": ErrorCodes.NOT_FOUND,
    "throttled": ErrorCodes.THROTTLED,
    "method_not_allowed": ErrorCodes.METHOD_NOT_ALLOWED,
    "invalid": ErrorCodes.VALIDATION_ERROR,
    "error": ErrorCodes.SERVER_ERROR,
}