# Generated by Django 5.2.17 on 2026-08-28 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IslandTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('asset', 'Asset')], max_length=10)),
                ('symbol', models.CharField(blank=True, help_text='Ticker for asset kind, e.g. SPY, BTC-USD', max_length=20, null=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Suggested annual rate, cash kind only', max_digits=6, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(default='#2563EB', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('savings', 'Savings'), ('emergency', 'Emergency'), ('investment', 'Investment'), ('leisure', 'Leisure'), ('expenses', 'Expenses')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('asset', 'Asset')], max_length=10)),
                ('currency', models.CharField(blank=True, help_text='Cash islands, e.g. MXN, USD', max_length=10, null=True)),
                ('symbol', models.CharField(blank=True, help_text='Asset islands, e.g. BTC-USD, SPY', max_length=20, null=True)),
                ('interest_type', models.CharField(blank=True, choices=[('simple', 'Simple'), ('compound', 'Compound')], help_text='Cash islands only', max_length=10, null=True)),
                ('annual_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Current annual rate, cash islands only', max_digits=6, null=True)),
                ('color', models.CharField(default='#0EA5E9', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islands', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islands', to='portfolio.islandtemplate')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islands', to='portfolio.module')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
