# Generated by Django 5.2.17 on 2026-09-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IslandTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('asset', 'Asset')], max_length=10)),
                ('symbol', models.CharField(blank=True, help_text='Asset islands, e.g. BTC-USD, SPY', max_length=20, null=True)),
                ('asset_type', models.CharField(blank=True, choices=[('crypto', 'Crypto'), ('stock', 'Stock')], help_text='Required when kind=asset, e.g. crypto or stock', max_length=10, null=True)),
                ('default_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Suggested annual rate, cash kind only', max_digits=6, null=True)),
                ('logo_url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(default='#2563EB', max_length=7)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('savings', 'Savings'), ('emergency', 'Emergency'), ('investment', 'Investment'), ('leisure', 'Leisure'), ('expenses', 'Expenses')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('cash', 'Cash'), ('asset', 'Asset')], max_length=10)),
                ('currency', models.CharField(blank=True, help_text='Native currency for display: cash islands (user-set, e.g. MXN/USD) or asset islands (from provider, e.g. USD for crypto/US stocks, MXN for BMV)', max_length=10, null=True)),
                ('symbol', models.CharField(blank=True, help_text="Asset islands, provider-ready symbol, e.g. 'bitcoin' (CoinGecko id) or 'SPY' (Twelve Data ticker)", max_length=20, null=True)),
                ('asset_type', models.CharField(blank=True, choices=[('crypto', 'Crypto'), ('stock', 'Stock')], help_text='Required when kind=asset, e.g. crypto or stock', max_length=10, null=True)),
                ('interest_type', models.CharField(blank=True, choices=[('simple', 'Simple'), ('compound', 'Compound')], help_text='Cash islands only', max_length=10, null=True)),
                ('annual_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Current annual rate, cash islands only', max_digits=6, null=True)),
                ('color', models.CharField(default='#0EA5E9', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islands', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islands', to='portfolio.islandtemplate')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islands', to='portfolio.module')),
            ],
            options={
                'ordering': ['created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('kind', 'asset'), _negated=True), ('asset_type__isnull', False), _connector='OR'), name='asset_island_requires_asset_type')],
            },
        ),
    ]
