# Generated by Django 5.2.17 on 2026-09-03 21:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20260828_1629'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('crypto', 'Crypto'), ('stock', 'Stock')], help_text='Required when kind=asset, e.g. crypto or stock', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='islandtemplate',
            name='asset_type',
            field=models.CharField(blank=True, choices=[('crypto', 'Crypto'), ('stock', 'Stock')], help_text='Required when kind=asset, e.g. crypto or stock', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='island',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='island',
            name='symbol',
            field=models.CharField(blank=True, help_text="Asset islands, provider-ready symbol, e.g. 'bitcoin' (CoinGecko id) or 'SPY' (Twelve Data ticker)", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='islandtemplate',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='islandtemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='islandtemplate',
            name='symbol',
            field=models.CharField(blank=True, help_text='Asset islands, e.g. BTC-USD, SPY', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Solo informativo: fecha de la última desactivación. No se usa para lógica de negocio.', null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='island',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'asset'), _negated=True), ('asset_type__isnull', False), _connector='OR'), name='asset_island_requires_asset_type'),
        ),
    ]
