# Generated by Django 5.2.17 on 2026-09-14 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_seed_island_templates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='island',
            name='currency',
            field=models.CharField(blank=True, choices=[('MXN', 'MXN'), ('USD', 'USD')], help_text='Native currency for display: cash islands (user-set, e.g. MXN/USD) or asset islands (from provider, e.g. USD for crypto/US stocks, MXN for BMV)', max_length=3, null=True),
        ),
        migrations.AddConstraint(
            model_name='island',
            constraint=models.CheckConstraint(condition=models.Q(('currency__isnull', True), ('currency__in', ['MXN', 'USD']), _connector='OR'), name='currency_must_be_mxn_or_usd'),
        ),
    ]
