# Generated by Django 5.2.17 on 2026-09-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_island_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='is_system',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='module',
            name='is_system',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='type',
            field=models.CharField(choices=[('savings', 'Savings'), ('emergency', 'Emergency'), ('investment', 'Investment'), ('leisure', 'Leisure'), ('expenses', 'Expenses'), ('cash', 'Cash')], max_length=20),
        ),
    ]
