# Generated by Django 5.2.17 on 2026-09-17 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_island_is_system_module_is_system_alter_module_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='island',
            name='mic_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
